--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: administrativo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.administrativo (
    id bigint NOT NULL,
    cargo character varying(255) NOT NULL,
    departamento character varying(255) NOT NULL
);


ALTER TABLE public.administrativo OWNER TO postgres;

--
-- Name: curso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.curso (
    id bigint NOT NULL,
    creditos integer NOT NULL,
    descripcion character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    id_profesor bigint NOT NULL,
    CONSTRAINT curso_creditos_check CHECK ((creditos >= 1))
);


ALTER TABLE public.curso OWNER TO postgres;

--
-- Name: curso_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.curso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.curso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estudiante; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estudiante (
    id bigint NOT NULL,
    grado integer NOT NULL,
    numero_matricula character varying(255) NOT NULL
);


ALTER TABLE public.estudiante OWNER TO postgres;

--
-- Name: inscripcion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inscripcion (
    id bigint NOT NULL,
    fecha_inscripcion date NOT NULL,
    id_curso bigint NOT NULL,
    id_estudiante bigint NOT NULL
);


ALTER TABLE public.inscripcion OWNER TO postgres;

--
-- Name: inscripcion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inscripcion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inscripcion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persona (
    id bigint NOT NULL,
    apellido character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    fecha_nacimiento date,
    nombre character varying(255) NOT NULL,
    telefono character varying(255)
);


ALTER TABLE public.persona OWNER TO postgres;

--
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profesor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profesor (
    id bigint NOT NULL,
    especialidad character varying(255) NOT NULL,
    fecha_contratacion date NOT NULL
);


ALTER TABLE public.profesor OWNER TO postgres;

--
-- Data for Name: administrativo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.administrativo (id, cargo, departamento) FROM stdin;
\.


--
-- Data for Name: curso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.curso (id, creditos, descripcion, nombre, id_profesor) FROM stdin;
\.


--
-- Data for Name: estudiante; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estudiante (id, grado, numero_matricula) FROM stdin;
\.


--
-- Data for Name: inscripcion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inscripcion (id, fecha_inscripcion, id_curso, id_estudiante) FROM stdin;
\.


--
-- Data for Name: persona; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.persona (id, apellido, email, fecha_nacimiento, nombre, telefono) FROM stdin;
\.


--
-- Data for Name: profesor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.profesor (id, especialidad, fecha_contratacion) FROM stdin;
\.


--
-- Name: curso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.curso_id_seq', 1, false);


--
-- Name: inscripcion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inscripcion_id_seq', 1, false);


--
-- Name: persona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.persona_id_seq', 1, false);


--
-- Name: administrativo administrativo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administrativo
    ADD CONSTRAINT administrativo_pkey PRIMARY KEY (id);


--
-- Name: curso curso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso
    ADD CONSTRAINT curso_pkey PRIMARY KEY (id);


--
-- Name: estudiante estudiante_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estudiante
    ADD CONSTRAINT estudiante_pkey PRIMARY KEY (id);


--
-- Name: inscripcion inscripcion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inscripcion
    ADD CONSTRAINT inscripcion_pkey PRIMARY KEY (id);


--
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id);


--
-- Name: profesor profesor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT profesor_pkey PRIMARY KEY (id);


--
-- Name: estudiante uknxwg5kyigirv4nsc5vcwvixvy; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estudiante
    ADD CONSTRAINT uknxwg5kyigirv4nsc5vcwvixvy UNIQUE (numero_matricula);


--
-- Name: estudiante fk25y07ljo5a3ibywdt5p4uchtr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estudiante
    ADD CONSTRAINT fk25y07ljo5a3ibywdt5p4uchtr FOREIGN KEY (id) REFERENCES public.persona(id);


--
-- Name: profesor fk3s5vdutxb00ftmsqftw0vof5m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT fk3s5vdutxb00ftmsqftw0vof5m FOREIGN KEY (id) REFERENCES public.persona(id);


--
-- Name: administrativo fk615eb4o7px2u1wi9dlwb7xqko; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administrativo
    ADD CONSTRAINT fk615eb4o7px2u1wi9dlwb7xqko FOREIGN KEY (id) REFERENCES public.persona(id);


--
-- Name: inscripcion fk6sw931ij561k2fq5sx4xonmlr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inscripcion
    ADD CONSTRAINT fk6sw931ij561k2fq5sx4xonmlr FOREIGN KEY (id_curso) REFERENCES public.curso(id);


--
-- Name: inscripcion fk8hgaf3r1wwea199gneh6m8035; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inscripcion
    ADD CONSTRAINT fk8hgaf3r1wwea199gneh6m8035 FOREIGN KEY (id_estudiante) REFERENCES public.estudiante(id);


--
-- Name: curso fkenvwioi79avb9nl1xnw8n3hao; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso
    ADD CONSTRAINT fkenvwioi79avb9nl1xnw8n3hao FOREIGN KEY (id_profesor) REFERENCES public.profesor(id);


--
-- PostgreSQL database dump complete
--

